QUERYSMASH_USERNAME: 'support@querysmash.com'
QUERYSMASH_PASSWORD: 'QS9911LD!'
STRIPE_SECRET_KEY: 'sk_test_Qk8AuPkeNyuS4kft2r7HyS2x'
REDISTOGO_URL: 'redis://redistogo:950fcdc5f758872f9f258dcd3ca046eb@spadefish.redistogo.com:9444/'
RESQUE_PASSWORD: 'QS3806'
AWS_ACCESS_KEY_ID: 'AKIAITLMFAY4IXE6PPRA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_BUCKET: 'mywaltzingegypt'

