QUERYSMASH_USERNAME: 'support@querysmash.com'
QUERYSMASH_PASSWORD: 'QS9911LD!'
SECRET_TOKEN: '2dd2efc88d00823d138c01c6ba7fc00fb62a165bb22521ad366e9d11b02c7c174758a85f31b9cd63ad729b2ad96debc9cbe463c5b2f5cd0b4a027910d1b8d0d0'
STRIPE_SECRET_KEY: 'sk_test_Qk8AuPkeNyuS4kft2r7HyS2x'
REDISTOGO_URL: 'redis://redistogo:950fcdc5f758872f9f258dcd3ca046eb@spadefish.redistogo.com:9444/'
RESQUE_PASSWORD: 'QS3806'
KISSMETRICS_KEY: 'b8c3aeba48f02f3c1259d128a1edb7c81125fd84'
AWS_ACCESS_KEY_ID: 'AKIAITLMFAY4IXE6PPRA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_BUCKET: 'querysmash-dev'

